---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Namespace }}
  labels:
    app: {{ .Application }}
---
apiVersion: v1
kind: List
metadata:
  resourceVersion: ""
items:
- apiVersion: v1
  data:
    key.pem: {{ .ServerKey }}
    server.pem: {{ .ServerCert }}
  kind: Secret
  metadata:
    name: certificates
    namespace: {{ .Namespace }}
    labels:
      app: {{ .Application }}
  type: Opaque
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Application }}
  namespace: {{ .Namespace }}
  labels:
    app: {{ .Application }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Application }}
  template:
    metadata:
      labels:
        app: {{ .Application }}
    spec:
      containers:
      - image: gmalbrand/admission-controller:latest
        name: {{ .Application }}
        imagePullPolicy: Never
        ports:
        - name: adm-ctrl-port
          containerPort: {{ .Port }}
          protocol: TCP
        volumeMounts:
        - name: webhook-certs
          mountPath: /etc/certs
          readOnly: true
      volumes:
      - name: webhook-certs
        secret:
          secretName: certificates
---
apiVersion: v1
kind: Service
metadata:
  labels: 
    app: {{ .Application }}
  name: {{ .Service }}
  namespace: {{ .Namespace }}
spec:
  ports: 
  - port: 443
    protocol: TCP
    targetPort: adm-ctrl-port
  selector:
    app: {{ .Application }}
---
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating.{{ .Service }}.{{ .Namespace }}.svc.default
webhooks:
- name: validating.{{ .Service }}.{{ .Namespace }}.svc.default
  rules:
  - apiGroups:   [""]
    apiVersions: ["v1"]
    operations:  ["CREATE"]
    resources:   ["*"]
    scope:       "Namespaced"
  clientConfig:
    service:
      namespace: {{ .Namespace }}
      name: {{ .Service }}
      path: /validate
    caBundle: {{ .CACert }}
  admissionReviewVersions: ["v1"]
  sideEffects: None
  timeoutSeconds: 5
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating.{{ .Service }}.{{ .Namespace }}.svc.default
webhooks:
- name: mutating.{{ .Service }}.{{ .Namespace }}.svc.default
  rules:
  - apiGroups:   [""]
    apiVersions: ["v1"]
    operations:  ["CREATE"]
    resources:   ["services"]
    scope:       "Namespaced"
  clientConfig:
    service:
      namespace: {{ .Namespace }}
      name: {{ .Service }}
      path: /mutate
    caBundle: {{ .CACert }}
  admissionReviewVersions: ["v1"]
  sideEffects: None
  timeoutSeconds: 5
